sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t prod -f Dockerfile.dev .

script:
  - docker run prod npm run test -- --coverage
# -- --coverage is used to tell travis to exit from input wait from test command