sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t prod -f Dockerfile.dev .

script:
  - docker run -e CI=true USERNAME/docker-react npm run test
# -- --coverage is used to tell travis to exit from input wait from test command